name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Setup Nix cache
      uses: cachix/cachix-action@v13
      continue-on-error: true
      with:
        name: cuda-gtk
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build application with Nix
      run: |
        nix-shell --run "zig build -Doptimize=ReleaseFast"

    - name: Collect dependencies
      run: |
        mkdir -p package/bin
        mkdir -p package/lib

        # Copy executable
        cp zig-out/bin/CileExplorer package/bin/

        # Copy shared libraries (excluding system libs that are typically available)
        ldd zig-out/bin/CileExplorer | grep "=> /" | awk '{print $3}' | while read lib; do
          # Filter out very common system libraries
          if [[ ! "$lib" =~ (libc\.so|libm\.so|libpthread\.so|libdl\.so|librt\.so|ld-linux) ]]; then
            cp -v "$lib" package/lib/ || true
          fi
        done

        # Create wrapper script
        cat > package/CileExplorer << 'EOF'
        #!/bin/bash
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
        exec "$SCRIPT_DIR/bin/CileExplorer" "$@"
        EOF
        chmod +x package/CileExplorer

    - name: Create tarball
      run: |
        tar -czf CileExplorer-linux-x64.tar.gz -C package .

    - name: Calculate checksum
      run: |
        sha256sum CileExplorer-linux-x64.tar.gz > CileExplorer-linux-x64.tar.gz.sha256

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-linux-x64
        path: |
          CileExplorer-linux-x64.tar.gz
          CileExplorer-linux-x64.tar.gz.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-linux-x64.tar.gz
          CileExplorer-linux-x64.tar.gz.sha256
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - name: Build application
      run: |
        nix-shell --run "zig build -Doptimize=ReleaseFast"

    - name: Create AppDir structure
      run: |
        mkdir -p CileExplorer.AppDir/usr/bin
        mkdir -p CileExplorer.AppDir/usr/lib
        mkdir -p CileExplorer.AppDir/usr/share/applications
        mkdir -p CileExplorer.AppDir/usr/share/icons/hicolor/256x256/apps

        # Copy executable
        cp zig-out/bin/CileExplorer CileExplorer.AppDir/usr/bin/

        # Copy dependencies
        ldd zig-out/bin/CileExplorer | grep "=> /" | awk '{print $3}' | while read lib; do
          cp -v "$lib" CileExplorer.AppDir/usr/lib/ || true
        done

        # Create desktop file
        cat > CileExplorer.AppDir/usr/share/applications/cileexplorer.desktop << 'EOF'
        [Desktop Entry]
        Name=Cile Explorer
        Exec=CileExplorer
        Icon=cileexplorer
        Type=Application
        Categories=Utility;FileTools;
        EOF

        # Create AppRun script
        cat > CileExplorer.AppDir/AppRun << 'EOF'
        #!/bin/bash
        SELF=$(readlink -f "$0")
        HERE=${SELF%/*}
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        exec "${HERE}/usr/bin/CileExplorer" "$@"
        EOF
        chmod +x CileExplorer.AppDir/AppRun

        # Create a placeholder icon (you should replace this with actual icon)
        touch CileExplorer.AppDir/usr/share/icons/hicolor/256x256/apps/cileexplorer.png
        ln -s usr/share/icons/hicolor/256x256/apps/cileexplorer.png CileExplorer.AppDir/cileexplorer.png
        ln -s usr/share/applications/cileexplorer.desktop CileExplorer.AppDir/cileexplorer.desktop

    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Create AppImage
      run: |
        ARCH=x86_64 ./appimagetool-x86_64.AppImage --appimage-extract-and-run CileExplorer.AppDir CileExplorer-x86_64.AppImage
        chmod +x CileExplorer-x86_64.AppImage

    - name: Calculate checksum
      run: |
        sha256sum CileExplorer-x86_64.AppImage > CileExplorer-x86_64.AppImage.sha256

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-AppImage
        path: |
          CileExplorer-x86_64.AppImage
          CileExplorer-x86_64.AppImage.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-x86_64.AppImage
          CileExplorer-x86_64.AppImage.sha256
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-pkg-config
          unzip
          wget

    - name: Install Zig in MSYS2
      shell: msys2 {0}
      run: |
        wget https://ziglang.org/download/0.14.0/zig-windows-x86_64-0.14.0.zip
        unzip zig-windows-x86_64-0.14.0.zip
        mv zig-windows-x86_64-0.14.0 /c/zig
        echo "/c/zig" >> $GITHUB_PATH

    - name: Build application
      shell: msys2 {0}
      run: |
        export PATH="/c/zig:/mingw64/bin:$PATH"
        zig build -Doptimize=ReleaseFast

    - name: Collect dependencies
      shell: msys2 {0}
      run: |
        mkdir -p package

        # Copy executable
        cp zig-out/bin/CileExplorer.exe package/

        # Copy DLLs
        ldd zig-out/bin/CileExplorer.exe | grep mingw64 | awk '{print $3}' | while read dll; do
          cp -v "$dll" package/ || true
        done

        # Copy GTK runtime files
        mkdir -p package/share
        cp -r /mingw64/share/glib-2.0 package/share/ || true
        cp -r /mingw64/share/icons package/share/ || true
        cp -r /mingw64/share/themes package/share/ || true

    - name: Create zip archive
      run: |
        Compress-Archive -Path package\* -DestinationPath CileExplorer-windows-x64.zip

    - name: Calculate checksum
      run: |
        (Get-FileHash CileExplorer-windows-x64.zip -Algorithm SHA256).Hash | Out-File -FilePath CileExplorer-windows-x64.zip.sha256

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-windows-x64
        path: |
          CileExplorer-windows-x64.zip
          CileExplorer-windows-x64.zip.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-windows-x64.zip
          CileExplorer-windows-x64.zip.sha256
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Zig manually
      run: |
        wget https://ziglang.org/download/0.14.0/zig-macos-x86_64-0.14.0.tar.xz
        tar -xf zig-macos-x86_64-0.14.0.tar.xz
        sudo mv zig-macos-x86_64-0.14.0 /usr/local/zig
        echo "/usr/local/zig" >> $GITHUB_PATH

    - name: Verify Zig version
      run: |
        /usr/local/zig/zig version

    - name: Install dependencies
      run: |
        brew install gtk+3 pkg-config

    - name: Build application
      run: |
        /usr/local/zig/zig build -Doptimize=ReleaseFast

    - name: Create app bundle
      run: |
        mkdir -p CileExplorer.app/Contents/MacOS
        mkdir -p CileExplorer.app/Contents/Resources
        mkdir -p CileExplorer.app/Contents/Frameworks

        # Copy executable
        cp zig-out/bin/CileExplorer CileExplorer.app/Contents/MacOS/

        # Copy dependencies
        otool -L zig-out/bin/CileExplorer | grep -v /usr/lib | grep -v /System | awk '{print $1}' | tail -n +2 | while read lib; do
          if [ -f "$lib" ]; then
            cp -v "$lib" CileExplorer.app/Contents/Frameworks/ || true
          fi
        done

        # Create Info.plist
        cat > CileExplorer.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>CileExplorer</string>
            <key>CFBundleIdentifier</key>
            <string>com.cileexplorer.app</string>
            <key>CFBundleName</key>
            <string>Cile Explorer</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
        </dict>
        </plist>
        EOF

        # Fix library paths
        install_name_tool -add_rpath @executable_path/../Frameworks CileExplorer.app/Contents/MacOS/CileExplorer || true

    - name: Create DMG
      run: |
        # Create temporary directory for DMG contents
        mkdir -p dmg
        cp -R CileExplorer.app dmg/

        # Create DMG
        hdiutil create -volname "Cile Explorer" -srcfolder dmg -ov -format UDZO CileExplorer-macos-x64.dmg

    - name: Calculate checksum
      run: |
        shasum -a 256 CileExplorer-macos-x64.dmg > CileExplorer-macos-x64.dmg.sha256

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-macos-x64
        path: |
          CileExplorer-macos-x64.dmg
          CileExplorer-macos-x64.dmg.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-macos-x64.dmg
          CileExplorer-macos-x64.dmg.sha256
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
