name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Setup Nix cache
      uses: cachix/cachix-action@v13
      continue-on-error: true
      with:
        name: cuda-gtk
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build application with Nix
      run: |
        nix-shell --run "zig build -Doptimize=ReleaseFast"

    - name: Collect dependencies
      run: |
        mkdir -p package/bin
        mkdir -p package/lib

        # Copy executable
        cp zig-out/bin/CileExplorer package/bin/

        # Copy shared libraries (excluding system libs that are typically available)
        ldd zig-out/bin/CileExplorer | grep "=> /" | awk '{print $3}' | while read lib; do
          # Filter out very common system libraries
          if [[ ! "$lib" =~ (libc\.so|libm\.so|libpthread\.so|libdl\.so|librt\.so|ld-linux) ]]; then
            cp -v "$lib" package/lib/ || true
          fi
        done

        # Create wrapper script
        cat > package/CileExplorer << 'EOF'
        #!/bin/bash
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        export LD_LIBRARY_PATH="$SCRIPT_DIR/lib:$LD_LIBRARY_PATH"
        exec "$SCRIPT_DIR/bin/CileExplorer" "$@"
        EOF
        chmod +x package/CileExplorer

    - name: Create tarball
      run: |
        tar -czf CileExplorer-linux-x64.tar.gz -C package .

    - name: Calculate checksum
      run: |
        sha256sum CileExplorer-linux-x64.tar.gz > CileExplorer-linux-x64.tar.gz.sha256

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-linux-x64
        path: |
          CileExplorer-linux-x64.tar.gz
          CileExplorer-linux-x64.tar.gz.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-linux-x64.tar.gz
          CileExplorer-linux-x64.tar.gz.sha256
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-appimage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - name: Build application
      run: |
        nix-shell --run "zig build -Doptimize=ReleaseFast"

    - name: Create AppDir structure
      run: |
        mkdir -p CileExplorer.AppDir/usr/bin
        mkdir -p CileExplorer.AppDir/usr/lib
        mkdir -p CileExplorer.AppDir/usr/share/applications
        mkdir -p CileExplorer.AppDir/usr/share/icons/hicolor/256x256/apps

        # Copy executable
        cp zig-out/bin/CileExplorer CileExplorer.AppDir/usr/bin/

        # Copy dependencies
        ldd zig-out/bin/CileExplorer | grep "=> /" | awk '{print $3}' | while read lib; do
          cp -v "$lib" CileExplorer.AppDir/usr/lib/ || true
        done

        # Create desktop file
        cat > CileExplorer.AppDir/usr/share/applications/cileexplorer.desktop << 'EOF'
        [Desktop Entry]
        Name=Cile Explorer
        Exec=CileExplorer
        Icon=cileexplorer
        Type=Application
        Categories=Utility;FileTools;
        EOF

        # Create AppRun script
        cat > CileExplorer.AppDir/AppRun << 'EOF'
        #!/bin/bash
        SELF=$(readlink -f "$0")
        HERE=${SELF%/*}
        export PATH="${HERE}/usr/bin:${PATH}"
        export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
        exec "${HERE}/usr/bin/CileExplorer" "$@"
        EOF
        chmod +x CileExplorer.AppDir/AppRun

        # Create a placeholder icon (you should replace this with actual icon)
        touch CileExplorer.AppDir/usr/share/icons/hicolor/256x256/apps/cileexplorer.png
        ln -s usr/share/icons/hicolor/256x256/apps/cileexplorer.png CileExplorer.AppDir/cileexplorer.png
        ln -s usr/share/applications/cileexplorer.desktop CileExplorer.AppDir/cileexplorer.desktop

    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Create AppImage
      run: |
        ./appimagetool-x86_64.AppImage --appimage-extract-and-run CileExplorer.AppDir CileExplorer-x86_64.AppImage
        chmod +x CileExplorer-x86_64.AppImage

    - name: Calculate checksum
      run: |
        sha256sum CileExplorer-x86_64.AppImage > CileExplorer-x86_64.AppImage.sha256

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: CileExplorer-AppImage
        path: |
          CileExplorer-x86_64.AppImage
          CileExplorer-x86_64.AppImage.sha256
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CileExplorer-x86_64.AppImage
          CileExplorer-x86_64.AppImage.sha256
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
